development:
  cloud_name: dmfhkzsd9
  api_key: '633452127928929'
  api_secret: OEgXRQpqBB8c3QGNB6l0ckgLlFk
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dmfhkzsd9
  api_key: '633452127928929'
  api_secret: OEgXRQpqBB8c3QGNB6l0ckgLlFk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dmfhkzsd9
  api_key: '633452127928929'
  api_secret: OEgXRQpqBB8c3QGNB6l0ckgLlFk
  enhance_image_tag: true
  static_image_support: false
